### ISSUE TITLE
Submission: ploteasyr (R)

### ISSUE THREAD

**Issue by zhijingjing1** [UBC-MDS/software-review-2021#41]
Submitting Author: 
- Jingjing Zhi ([@zhijingjing1](https://github.com/zhijingjing1))
- Fei Chang ([@fei-chang](https://github.com/fei-chang))
- Mengyuan Zhu ([@Julie-M-Zhu](https://github.com/Julie-M-Zhu))
 
Repository: [ploteasyr](https://github.com/UBC-MDS/ploteasyr/tree/master)

Version submitted: [v0.3.0] ( https://github.com/UBC-MDS/ploteasyr/releases/tag/V0.3.0)

Editor:  TBD 

Reviewers:  TBD 

Archive: TBD

Version accepted: TBD

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: ploteasyr
Title: Plot easily with default theme and settings (One Line, Title Case)
Version: 0.0.0.9000
Authors@R: 
    person(given = "Mengyuan",
           family = "Zhu",
           role = c("aut", "cre"),
           email = "zhumengyuan@126.com"),
    person(given = "Jingjing",
           family = "Zhi",
           role = c("aut", "cre"),
           email = "jzhi079@uottawa.ca"),
    person(given = "Fei",
           family = "Chang",
           role = c("aut", "cre"),
           email = "fc1271@nyu.edu"))
    )
           
Description: Plot easily with default theme and settings.
License: GNU LICENSE
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
Imports: 
    ggplot2,
    dplyr,
    magrittr,
    testthat,
    palmerpenguins,
    stringr,
    ggthemes,
    utils,
    covr,
    imputeR,
    scales,
    tidyr,
    tidyselect,
    stats,
    rlang
Suggests: 
    testthat (>= 3.0.0)
Config/testthat/edition: 2
URL: https://github.com/UBC-MDS/ploteasyr/tree/master
BugReports: https://github.com/UBC-MDS/ploteasyr/issues

```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	- [x] data visualization  

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

ploteasyr offers beginner-friendly functions to do data visualizations. It has functionality to plot histogram, scatter plot and bar plot. The functions have build-in theme and other settings, which are complicated for the beginners of R but are compulsory for plotting in mainstream plotting packages like ggplot. 

-   Who is the target audience and what are scientific applications of this package?

The target audience would be people who are new to R and are interested in simple data visualization.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There are other R packages that accomplish the similar thing such as "SmartEDA" or "ggplot". However, ploteasyr is more friendly to new learner of R, easier to understand and focus on three kinds of plots. 

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Not applicable

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

Not applicable

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [ ] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by lephanthuymai** [comment]
Hi @zhijingjing1  and team,
I'm glad to be assigned to review your R package :)
Which version of the package should I use? It is stated as `v0.2.0` above, but the DESCRIPTION says `0.0.0.9000` and I found multiple releases in the repo, so I'm a bit confused.
Looking forward to your response so that I can finish the review on time.
Thanks.
Mai Le

**Comment by lephanthuymai** [comment]
Hi @zhijingjing1  and team,
Assuming the latest version [V0.3.0](https://github.com/UBC-MDS/ploteasyr/releases/tag/V0.3.0) is the right one, here are my review notes.

## Package Review

*Please check off boxes as applicable, and elaborate in the comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions
- [x] **Examples** (that run successfully locally) for all exported functions
- [x] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [ ] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

Estimated hours spent reviewing: 1 hour

- [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

Congratulations on completing your (assumably) first R package! Overall, I like the simplicity of this package, the functions are neat and easy to use for new R users.

There are some improvements that should be made if you expect to release this package to the public.

I would recommend writing more tests to verify the main functionality and more edge cases of the functions (they do not work on the famous `penguins` dataset).

`usethis` library conveniently supports us to create our package documents using the predefined templates, it is recommended to review and adjust their contents to fit our own package, see more details below.

#### README.md
I found some discrepancies between README.Rmd and README.md file, it seems like README.md was not generated from README.Rmd. README.md includes some information automatically generated from the template but irrelevant to the current package (`Example` section).

#### Installation
The package is not available on CRAN yet, so the installation guide to install from CRAN will not work. I was able to install the development version from Github.

#### CONTRIBUTING.md
It seems that the file was copied from the python package, it includes information on how to use `poetry`, which is not relevant to an R package.

#### Functionality

When trying this package on the `penguins` data set, I got the below errors.

```
> library(ploteasyr)
> library(palmerpenguins)
> plot_bar(penguins)
Using  as id variables
Error in match.names(clabs, names(xi)) : 
  names do not match previous names
  
> plot_hist(penguins)
Using  as id variables
Error in match.names(clabs, names(xi)) : 
  names do not match previous names

> plot_scatter(penguins)
Error: object '' not found
Run `rlang::last_error()` to see where the error occurred.
```

#### Unit test coverage
I retrieved the unit test coverage using `covr::report` and got the result of `26.09%`.

Looking into the tests, there are tests regarding some invalid inputs, but no test written for validating if the functions actually work.

------

Please let me know if you need any clarification on any point.

Again, congratulations on finishing the project and block 5, we are almost done!
Best,
Mai Le

**Comment by zhijingjing1** [comment]
> Hi @zhijingjing1 and team,
> I'm glad to be assigned to review your R package :)
> Which version of the package should I use? It is stated as `v0.2.0` above, but the DESCRIPTION says `0.0.0.9000` and I found multiple releases in the repo, so I'm a bit confused.
> Looking forward to your response so that I can finish the review on time.
> Thanks.
> Mai Le

**Comment by zhijingjing1** [comment]
Hi, Mai. Thank you so much for you feedback. I have updated the version.

**Comment by pan1fan2** [comment]
## Package Review

- **Briefly describe any working relationship you have (had) with the package authors.**
- [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions
- [x] **Examples** (that run successfully locally) for all exported functions
- [ ] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [ ] **Installation:** Installation succeeds as documented.
- [ ] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [x] **Automated tests:** Unit tests cover essential functions of the package
   and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

Estimated hours spent reviewing:

- [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

In summary:  Hey `ploteasyr` team,  thanks for making a swift plotting package for R beginners.  Installation instructions, vignettes are present. 

Below are my five constructive points:

1.  I suggest adding more to the README which would give users a little more description about this package. Also, it would be helpful to include features and usages regarding each function in README.  Besides, adding contribution guidelines would help it conform a bit more to the packaging guidelines.

2. The package can only be installed through Github for now. So I think it would be great to remove CRAN instruction to avoid confusion.

3.  The documentation for functions in the package is comprehensive and contains examples.  The functions are readable, comprehensive, self-protective and able to deal with the exceptions.  I can also see `R-CMD-check` and `test-coverage` from Github actions for automated tests. But it would be great to see the bages/test reports.

4. Though tests in plot_hist() and plot_bar() can cover inputs,  I am not familiar with testing faceted plots so it might be very difficult to include tests to cover output. If possible, it would be great to include tests on output.

5.  I tested the code with a toy dataframe , the functions worked well, I saw 3 plots, but I think it would be great to include more varieties, for example, a density plot overlaid on the bar plot? Just a matter of personal taste.

```{r}
df <- data.frame(num1 = c(8.5, 8, 9.2, 9.1, 9.4),
                 num2 = c(0.88, 0.93, 0.95 , 0.92 , 0.91),
                 num3 = c(0.46, 0.78, 0.66, 0.69, 0.52),
                 num4 = c(0.082, 0.078, 0.082, 0.085, 0.066),
                 cat1 = c("Good","Okay","Excellent","Terrible","Good"),
                 target = c(2,2,3,1,3))
library(ploteasyr)
plot_bar(df)
plot_hist(df)
df$cat1 = as.factor(df$cat1)
plot_scatter(df,num1,num2,cat1,"test")
```
