### ISSUE TITLE
Submission: NiceNumber (Python)

### ISSUE THREAD

**Issue by jaymegordo** [UBC-MDS/software-review-2021#8]
Submitting Authors:
- Cameron Harris(@camharris22)
- Jayme Gordon (@jaymegordo)
- Guanshu Tao (@GuanshuTao)
- Zhiyong Wang (@wiwang)

Package Name: NiceNumber
One-Line Description of Package: NiceNumber is a package to convert numbers to concise human-readable strings.
Repository Link: [NiceNumber](https://github.com/UBC-MDS/NiceNumber)
Version submitted: [v0.2.5](https://github.com/UBC-MDS/NiceNumber/releases/tag/v0.2.5)
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

## Description

Large numbers can be difficult to display and hard for humans to comprehend/compare in their full form. NiceNumber simplifies the conversion of numbers to human-readable representaions with the use of multiple classes of suffixes, eg `1345948349 > '1.35B' or '1.35GB'`. The package also has functions to convert from these strings back to raw numbers, convert entire columns of pandas dataframes, and colour-code sections of the number.

## Scope 
- Please indicate which [category or categories][PackageCategories] this package falls under:
	- [ ] Data retrieval
	- [ ] Data extraction
	- [x] Data munging
	- [ ] Data deposition
	- [ ] Reproducibility
	- [ ] Geospatial
	- [ ] Education
	- [ ] Data visualization*

\* Please fill out a pre-submission inquiry before submitting a data visualization package. For more info, see [notes on categories][NotesOnCategories] of our guidebook.

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences):
> NiceNumber is entirely based around data munging/wrangling, eg transforming data from a raw to a more easily understandable format.

-   Who is the target audience and what are scientific applications of this package?
> The target audience is anyone who may need to display large numbers in a more readable format, eg in pandas dataframes, or for GUI display to a user in applications or dashboards.

-   Are there other Python packages that accomplish the same thing? If so, how does yours differ?
>[`numerize`](https://github.com/davidsa03/numerize) converts large numbers like 1234567.12 into 1.23M.
>[`humanreadable`](https://github.com/thombashi/humanreadable) converts from human-readable values to Python values.
>
> Our package combines the forward/backward conversions of both these packages, simplifies usage, and adds other helper functions like dataframe compatibility and coloring.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or `@tag` the editor you contacted:

## Technical checks

For details about the pyOpenSci packaging requirements, see our [packaging guide][PackagingGuide]. Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has an [OSI approved license][OsiApprovedLicense].
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration, such as Travis CI, AppVeyor, CircleCI, and/or others.

## Publication options

- [ ] Do you wish to automatically submit to the [Journal of Open Source Software][JournalOfOpenSourceSoftware]? If so:

<details>
 <summary>JOSS Checks</summary>  

- [ ] The package has an **obvious research application** according to JOSS's definition in their [submission requirements][JossSubmissionRequirements]. Be aware that completing the pyOpenSci review process **does not** guarantee acceptance to JOSS. Be sure to read their submission requirements (linked above) if you are interested in submitting to JOSS.
- [ ] The package is not a "minor utility" as defined by JOSS's [submission requirements][JossSubmissionRequirements]: "Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable." pyOpenSci welcomes these packages under "Data Retrieval", but JOSS has slightly different criteria.
- [ ] The package contains a `paper.md` matching [JOSS's requirements][JossPaperRequirements] with a high-level description in the package root or in `inst/`.
- [ ] The package is deposited in a long-term repository with the DOI: 

*Note: Do not submit your package separately to JOSS*
  
</details>

## Are you OK with Reviewers Submitting Issues and/or pull requests to your Repo Directly?
This option will allow reviewers to open smaller issues that can then be linked to PR's rather than submitting a more dense text based review. It will also allow you to demonstrate addressing the issue via PR links.

- [x] Yes I am OK with reviewers submitting requested changes as issues to my repo. Reviewers will then link to the issues in their submitted review.

## Code of conduct

- [x] I agree to abide by [pyOpenSci's Code of Conduct][PyOpenSciCodeOfConduct] during the review process and in maintaining my package should it be accepted.

**P.S.** *Have feedback/comments about our review process? Leave a comment [here][Comments]

## Editor and Review Templates

[Editor and review templates can be found here][Templates]

[PackagingGuide]: https://www.pyopensci.org/contributing-guide/authoring/index.html#packaging-guide

[PackageCategories]: https://www.pyopensci.org/contributing-guide/open-source-software-peer-review/aims-and-scope.html?highlight=data#package-categories

[NotesOnCategories]: https://www.pyopensci.org/contributing-guide/open-source-software-peer-review/aims-and-scope.html?highlight=data#notes-on-categories

[JournalOfOpenSourceSoftware]: http://joss.theoj.org/

[JossSubmissionRequirements]: https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements

[JossPaperRequirements]: https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

[PyOpenSciCodeOfConduct]: https://www.pyopensci.org/contributing-guide/open-source-software-peer-review/code-of-conduct.html?highlight=code%20conduct

[OsiApprovedLicense]: https://opensource.org/licenses

[Templates]: https://www.pyopensci.org/contributing-guide/appendices/templates.html

[Comments]: https://github.com/pyOpenSci/governance/issues/8

**Comment by hellosakshi** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*

- [X] As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [X] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [X] **Function Documentation:** for all user-facing functions
- [X] **Examples** for all user-facing functions
- [X] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING.
- [ ] **Metadata** including author(s), author e-mail(s), a url, and any other relevant metadata e.g., in a `setup.py` file or elsewhere.

Readme requirements
The package meets the readme requirements below:

- [X] Package has a README.md file in the root directory.

The README should include, from top to bottom:

- [X] The package name
- [X] Badges for continuous integration and test coverage, a repostatus.org badge, and any other badges. If the README has many more badges, you might want to consider using a table for badges: [see this example](https://github.com/ropensci/drake). Such a table should be more wide than high. (Note that the badge for pyOpenSci peer-review will be provided upon acceptance.)
- [x] Short description of goals of package, with descriptive links to all vignettes (rendered, i.e. readable, cf the documentation website section) unless the package is small and there’s only one vignette repeating the README.
- [ ] Installation instructions
- [ ] Any additional setup required (authentication tokens, etc)
- [x] Brief demonstration usage
- [x] Direction to more detailed documentation (e.g. your documentation files or website).
- [x] If applicable, how the package compares to other similar packages and/or how it relates to other packages
- [x] Citation information

#### Usability
Reviewers are encouraged to submit suggestions (or pull requests) that will improve the usability of the package as a whole.
Package structure should follow general community best-practices. In general please consider:

- [x] The documentation is easy to find and understand
- [x] The need for the package is clear
- [x] All functions have documentation and associated examples for use


#### Functionality

- [ ] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [x] **Automated tests:** Tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [x] **Continuous Integration:** Has continuous integration, such as Travis CI, AppVeyor, CircleCI, and/or others.
- [x] **Packaging guidelines**: The package conforms to the pyOpenSci [packaging guidelines](https://www.pyopensci.org/dev_guide/authoring/overview.html).

#### For packages co-submitting to JOSS

- [ ] The package has an **obvious research application** according to JOSS's definition in their [submission requirements](http://joss.theoj.org/about#submission_requirements).

*Note:* Be sure to check this carefully, as JOSS's submission requirements and scope differ from pyOpenSci's in terms of what types of packages are accepted.

The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with:

- [ ] **A short summary** describing the high-level functionality of the software
- [ ] **Authors:** A list of authors with their affiliations
- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience.
- [ ] **References:** with DOIs for all those that have one (e.g. papers, datasets, software).

#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing:

---

#### Review Comments
1. I am not able install the package. The error message was: You must give at least one requirement to install (see "pip help install").
2. I am not able to open Contributors page. It's taking me to 404 page.
3. I believe Metadata (** including author(s), author e-mail(s), a url, and any other relevant metadata) is missing.
4. One Badges: "Release" is missing.
5. I like the overall work. Specially good job including other packages with similar functions. This makes the purpose of the function much clearer to anyone reviewing the package.

**Comment by jaymegordo** [comment]
@hellosakshi I'm very sorry about the url, I removed the space from the link not realizing it was required... could you please install with:
`pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple nicenumber`

and then import the package with:
`from nicenumber import nicenumber as nn`

Thanks and sorry again about that!

**Comment by shoebillm** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*

- [X] As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [X] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [X] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [X] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [X] **Function Documentation:** for all user-facing functions
- [X] **Examples** for all user-facing functions
- [X] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING.
- [ ] **Metadata** including author(s), author e-mail(s), a url, and any other relevant metadata e.g., in a `setup.py` file or elsewhere.

Readme requirements
The package meets the readme requirements below:

- [X] Package has a README.md file in the root directory.

The README should include, from top to bottom:

- [X] The package name
- [X] * Badges for continuous integration and test coverage, a repostatus.org badge, and any other badges. If the README has many more badges, you might want to consider using a table for badges: [see this example](https://github.com/ropensci/drake). Such a table should be more wide than high. (Note that the badge for pyOpenSci peer-review will be provided upon acceptance.)
- [X] Short description of goals of package, with descriptive links to all vignettes (rendered, i.e. readable, cf the documentation website section) unless the package is small and there’s only one vignette repeating the README.
- [X] Installation instructions
- [ ] Any additional setup required (authentication tokens, etc)
- [X] Brief demonstration usage
- [X] Direction to more detailed documentation (e.g. your documentation files or website).
- [X] If applicable, how the package compares to other similar packages and/or how it relates to other packages
- [X] Citation information

#### Usability
Reviewers are encouraged to submit suggestions (or pull requests) that will improve the usability of the package as a whole.
Package structure should follow general community best-practices. In general please consider:

- [X] The documentation is easy to find and understand
- [X] The need for the package is clear
- [X] All functions have documentation and associated examples for use


#### Functionality

- [X] **Installation:** Installation succeeds as documented.
- [ ] **Functionality:** Any functional claims of the software been confirmed.
- [ ] **Performance:** Any performance claims of the software been confirmed.
- [X] **Automated tests:** Tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [X] **Continuous Integration:** Has continuous integration, such as Travis CI, AppVeyor, CircleCI, and/or others.
- [X] **Packaging guidelines**: The package conforms to the pyOpenSci [packaging guidelines](https://www.pyopensci.org/dev_guide/authoring/overview.html).

#### For packages co-submitting to JOSS

- [ ] The package has an **obvious research application** according to JOSS's definition in their [submission requirements](http://joss.theoj.org/about#submission_requirements).

*Note:* Be sure to check this carefully, as JOSS's submission requirements and scope differ from pyOpenSci's in terms of what types of packages are accepted.

The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with:

- [ ] **A short summary** describing the high-level functionality of the software
- [ ] **Authors:** A list of authors with their affiliations
- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience.
- [ ] **References:** with DOIs for all those that have one (e.g. papers, datasets, software).

#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing: 1.5 hr

---

#### Review Comments

Overall, it is a very interesting package that does some essential data transformation work and it can be easily understood and used! I really like the idea that you group came up with: to convert the numbers from or to human-readable format, and this could be very useful in combination with other visualization packages! 

*The release badge is broken and it might be better to remove it.

I have a few comments for your documents or functions (using your updated installation instruction, I was able to install the package):
1. In your Features (from README.md), 
```python
n = 1234.5
nn.to_human(n=n, precision=1, family='number') 
```
This example would not work as you stated to produce "1.2K", instead, it always produces "1K" no matter how I changed the `precision` argument. I went through your function file and found out the argument name was `prec`, and you might want to change it to `precision` . 

Also, for this function, 
```python
n = -2
nn.to_human(n=n, precision=0, family='filesize')
```
It might be better to throw an error or warning message to the user when the converting a number to file size as it always has to be non-negative.

2. In your Features (from README.md),
```python
from nicenumber import nicenumber as nn

df = pd.DataFrame(np.array([[1_000, 1_000_000], [1_000_000_000, 1_000_000_000_000]]), columns=['A', 'B'])

nn.to_pandas(df, columns=['A'], transform_type='human')
```
This example needs other dependencies to be installed (pandas and numpy), and you might want to include all dependencies to construct a fully reproducible example. In addition, this function does not produce a dataframe as claimed. I went through the function file and found out the argument name was `col_names`, so you might want to change either one for consistency purpose.

3. For the function `nn.to_to_numeric()`, when I tried to input the string as non-numeric values, the error message is a bit vague: `TypeError: 'NoneType' object is not subscriptable`. You might want to add an exception handling to say the string must be a valid number.

4. In your Features (from README.md), it would be more clear to include the "print" statement:
`print(nn.to_color(1234567, ['green', 'red', 'blue']))` as the output can only be colored numbers when you print them out.
